version: '3.4'
services:
  trustlines-netstats.dnp.dappnode.eth:
    image: 'trustlines-netstats.dnp.dappnode.eth:0.1.1'
    build: ./build
    environment:
      - NETSTATS_ENABLE=no
      - WS_USER
      - WS_PASSWORD
      - INSTANCE_NAME
      - SHOW_VALIDATOR_STATUS=no
    restart: on-failure
