version: '3.4'
services:
  trustlines-netstats.dnp.dappnode.eth:
    image: 'trustlines-netstats.dnp.dappnode.eth:0.1.0'
    build: ./build
    environment:
      - NETSTATS_ENABLE
      - WS_USER
      - WS_PASSWORD
      - INSTANCE_NAME
      - SHOW_VALIDATOR_STATUS
    restart: on-failure
